# <center>PythonBasics: ProgrammingAssignment_08</center>


1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

### Question 1: Write a Python Program to Add Two Matrices?

In [1]:
def add_matrices(matrix1, matrix2):
    rows = len(matrix1)
    cols = len(matrix1[0])

    if rows != len(matrix2) or cols != len(matrix2[0]):
        return None

    result = []
    for i in range(rows):
        row = []
        for j in range(cols):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)

    return result

######### TEST
######## TEST
######## TEST

matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result_matrix = add_matrices(matrix1, matrix2)

if result_matrix:
    print("The sum of the matrices is:")
    for row in result_matrix:
        print(row)
else:
    print("The matrices cannot be added.")


The sum of the matrices is:
[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [6]:
################ METHOD 2 ##############
################ METHOD 2 ##############
################ METHOD 2 ##############


import numpy as np

def add_matrices(matrix1, matrix2):
    return np.add(matrix1, matrix2)

############## TEST
############### TEST
################ TEST

matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

result_matrix = add_matrices(matrix1, matrix2)

print("The sum of the matrices is:")
print(result_matrix)



The sum of the matrices is:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


### Question 2: Write a Python Program to Multiply Two Matrices?

In [7]:
import numpy as np

def multiply_matrices(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

################### TEST
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

result_matrix = multiply_matrices(matrix1, matrix2)

print("The product of the matrices is:")
print(result_matrix)


The product of the matrices is:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [8]:
################ METHOD 2 #################
################ METHOD 2 #################
################ METHOD 2 #################


def multiply_matrices(matrix1, matrix2):
    rows1 = len(matrix1)
    cols1 = len(matrix1[0])
    rows2 = len(matrix2)
    cols2 = len(matrix2[0])

    if cols1 != rows2:
        return None

    result = [[0] * cols2 for _ in range(rows1)]

    for i in range(rows1):
        for j in range(cols2):
            for k in range(cols1):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# TEST
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix2 = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]

result_matrix = multiply_matrices(matrix1, matrix2)

if result_matrix:
    print("The product of the matrices is:")
    for row in result_matrix:
        print(row)
else:
    print("The matrices cannot be multiplied.")


The product of the matrices is:
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


### Question 3 Write a Python Program to Transpose a Matrix?

In [9]:
def transpose_matrix(matrix):
    rows = len(matrix)
    cols = len(matrix[0])

    transposed = [[0] * rows for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix[i][j]

    return transposed

##### TEST#######
##### TEST#######
##### TEST#######

matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

transposed_matrix = transpose_matrix(matrix)

print("The transposed matrix is:")
for row in transposed_matrix:
    print(row)


The transposed matrix is:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [10]:
############ METHOD 2 ##############
############ METHOD 2 ##############
############ METHOD 2 ##############


import numpy as np

def transpose_matrix(matrix):
    return np.transpose(matrix)

################### TEST
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

transposed_matrix = transpose_matrix(matrix)

print("The transposed matrix is:")
print(transposed_matrix)


The transposed matrix is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Question 4: Write a Python Program to Sort Words in Alphabetic Order?

In [16]:
def sort_words(words, reverse_order=False):
    sorted_words = sorted(words,reverse=reverse_order)
    return sorted_words

########### TEST
########### TEST

words = input("Enter words separated by spaces: ").split()

sorted_words = sort_words(words, reverse_order=False)

print("Words in alphabetical order:")
for word in sorted_words:
    print(word)


Enter words separated by spaces:  M Junaid


Words in alphabetical order:
Junaid
M


In [36]:
# logical operation on string will compare lexicographic order. 'a' comes before z so the condition a < z is True

if 'a' < 'z':
    print(True)
else:
    print(False)

True


### Question 5: Write a Python Program to Remove Punctuation From a String?

In [46]:
########## METHOD1
########## METHOD1
########## METHOD1



import string

def remove_punctuation(text):
    # Create a translation table to remove punctuation
    translator = str.maketrans("", "", string.punctuation)
    
    # Remove punctuation using the translation table
    text_without_punctuation = text.translate(translator)
    
    return text_without_punctuation

############## TEST
text = "Hello, World!"
text_without_punctuation = remove_punctuation(text)

print("Text without punctuation:", text_without_punctuation)


Text without punctuation: Hello World


In [43]:
############ METHOD 2 ###################
############ METHOD 2 ###################
############ METHOD 2 ###################


import nltk
from nltk.tokenize import word_tokenize
import string

def remove_punctuation(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Remove punctuation from each word
    words_without_punctuation = [word for word in words if word not in string.punctuation]
    
    # Join the words back into a string
    text_without_punctuation = ' '.join(words_without_punctuation)
    
    return text_without_punctuation

################ TEST
#################### TEST
################## TEST

text = "Hello, World!"
text_without_punctuation = remove_punctuation(text)

print("Text without punctuation:", text_without_punctuation)


Text without punctuation: Hello World
